baseurl: /
paginate: 6
paginate_path: "page:num"
highlighter: pygments
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
permalink: /:year/:month-:day/:title.html
excerpt_separator: "<!-- ## -->"
author: "shaozilee"
# Gems
gems: [jekyll-paginate]
